### ISSUE TITLE
depselect does not work when php debug is enabled

### ISSUE THREAD

**Issue by rchovan** [shannah/xataface#60]
when I enable PHP debug, then depselect is not populated with data
index.php:
`````
ini_set ( 'display_errors' , 1 ) ;
error_reporting ( E_ALL ) ;
error_reporting ( -1 ) ;
error_reporting ( E_ALL ^ E_NOTICE ) ;
`````

**Comment by shannah** [comment]
This is probably due to error reporting writing errors to the browser.  Some of the ajax actions respond with JSON or XML so errors written to response will cause the JSON to appear corrupted.  You can view the raw responses to XHR (ajax) requests in the chrome console (network tab) to see what the errors are. They are probably just warnings, but you can either work on fixing those, or just don't write out notices.
